### ISSUE TITLE
add support for :foreign-libs

### ISSUE THREAD

**Issue by gmp26** [bensu/doo#162] opened 2018-01-15 17:20 UTC
It's not clear how to make the new compiler :foreign-libs option  work in a `lein doo phantom test` run.

For example in project.clj:
```clojure
 :foreign-libs  [{:file        "src/js/predict2model.js"
                                                :provides    ["js.predict2model"]
                                                :module-type :es6}]
```
where src/js/predict2model.js has the line
```
goog.provide('js.predict2model');
```
we get the error
```
TypeError: undefined is not an object (evaluating 'goog.provide')
```
But where should this be declared?

Also, if there's a :global-options key, lein-doo throws a wobbly.

**Comment by miikka** [comment] 2018-03-12 19:13
Doo doesn't do anything special with the `:foreign-libs` so I believe it should work out of the box. To me this looks more like ClojureScript configuration problem more than Doo problem. ClojureScript's documentation is the best reference for this:

* [`:foreign-libs` configuration option](https://clojurescript.org/reference/compiler-options#foreign-libs)
* [JS Module Support](https://clojurescript.org/reference/javascript-module-support)
* [Global Exports for Foreign Libraries](https://clojurescript.org/news/2017-07-30-global-exports)

Unfortunately, I'm not able to reproduce your problem with Doo and ClojureScript 1.9.946. Furthermore, I'm not 100% sure I understand what's your goal since your `predict2model.js` is a Google Closure module, but you have specified `:module-type :es6`.

I'm going to close this issue, but if you need more help, I recommend joining the #clojurescript channel on Clojurians slack and asking there. [You can get invite here](http://clojurians.net/)

---

The `:global-options` should be solved by #172 which will be included in the next release.

**Closed by miikka** 2018-03-12 19:13 UTC
