### ISSUE TITLE
Changing macro requires restarting process and triggering reload

### ISSUE THREAD

**Issue by exupero** [bensu/doo#51] opened 2015-10-26 10:32 UTC
I have several macros used by tests, and any time I change one of them, I have to stop the `lein doo` process and restart it, then (usually) touch my test file so doo recompiles the JS and runs the updated code. If I don't touch the test file, doo seems to use the original macro definition instead of the updated one.

**Comment by bensu** [comment] 2015-10-26 12:17
I think this is related to #52 and how the compiler finds/watches macro files. Since this is a little more complex, can you provide an example repo?

**Comment by exupero** [comment] 2015-10-27 01:36
I solved #52 by supplying a top-level `:source-paths` in my project.clj, but doo still doesn't pick up changes to .clj files. Here's an [example project](https://github.com/exupero/doo-macro-example) demonstrating the problem.

**Comment by bensu** [comment] 2015-10-27 09:29
Thanks @exupero , I'll look at it shortly.

**Comment by bensu** [comment] 2015-11-17 16:07
I was able to reproduce the behavior without using `doo` [here](https://github.com/bensu/clj-watch-repo). I'll see if we can fix this at the compiler level.

**Comment by bensu** [comment] 2015-11-23 16:44
Hey @exupero 

Macro reloading is not supported by the compiler's api. I think it is an important feature and doo should support it. Since we heavily rely on the compiler's api we will try to add it to the compiler. If that effort fails, we will refactor doo accordingly. In any case, it will take time :(

Sorry for the delay, I'll keep you posted.

**Comment by exupero** [comment] 2015-11-23 16:53
Thanks for your work on this. I'm in no urgent need of a fix and can work around the problem until the right solution is found.

**Comment by bensu** [comment] 2015-11-23 16:59
Cool, we'll be tracking progress on the compiler front in [CLJS-1490](http://dev.clojure.org/jira/browse/CLJS-1490).

**Comment by bensu** [comment] 2015-12-05 22:06
We got green light to fix this at the compiler level! Will update here any progress.

**Comment by lsenta** [comment] 2016-04-10 10:11
Note that I encounter this issue with `cljc` too,
will this fix the issue for both `clj` and `cljc`?

**Comment by bensu** [comment] 2016-04-11 09:50
Hi @lsenta, it seems that if I manage to solve it at the compiler level it should fix the problem for both `cljc` and `clj` files.

**Comment by metasoarous** [comment] 2016-05-12 17:30
Awesome that you're working on this; Status updates?

I'm working on a bunch of cljs macros, and it's sooo painful...

**Comment by bensu** [comment] 2016-05-12 20:15
Hi @metasoarous 

We need to go to `cljs.build.api/watch` and call something like [this function](https://github.com/clojure/tools.namespace/blob/master/src/main/clojure/clojure/tools/namespace/reload.clj#L15) when `clj` and `cljc` files need to be reloaded. I'll eventually get to it, but I don't know when since I've been super busy lately.

**Comment by metasoarous** [comment] 2016-05-12 20:48
OK; Sounds good. Looking forward to it :-)

**Comment by vemv** [comment] 2017-10-31 01:55
I'm not experiencing this issue (default config, no magic). I can touch a testing macro and suite will reload.

Issue might have become outdated?

**Comment by miikka** [comment] 2017-11-14 13:22
[CLJS-1490](https://dev.clojure.org/jira/browse/CLJS-1490) has been fixed. Therefore I believe this problem can be solved by upgrading to ClojureScript 1.9.198 or later. I'll close this issue now.

**Closed by miikka** 2017-11-14 13:22 UTC
Labels: bug
