### ISSUE TITLE
Don't close browser when tests finish

### ISSUE THREAD

**Issue by danielcompton** [bensu/doo#32] opened 2015-09-23 10:39 UTC
Is it possible to leave the browser up while running Karma tests? It would be really nice to not have the Chrome browser popping up and down when tests are auto running.

**Comment by bensu** [comment] 2015-09-24 17:23
This is possible and in the roadmap but it is very tough to get right! I'll get around it after I solve bigger problems related to getting karma working with `boot-cljs-test`.

**Comment by bensu** [comment] 2015-10-15 20:51
Fixed in d7c148cf1f37a6e494060ce6382219f9ac28adfb

@danielcompton do you mind trying it out? If you use `0.1.6-SNAPSHOT` and run `lein doo chrome test-build` you should see the intended behavior.

**Comment by danielcompton** [comment] 2015-10-17 02:34
Hey I've tried this out and it works great. Thanks! Just to confirm, we're not expecting test output to show up in the browser window?

![screenshot of google chrome 17-10-15 3 33 24 pm](https://cloud.githubusercontent.com/assets/811954/10556603/75efa028-74e4-11e5-8e9d-880e38ca6202.png)

Thanks!

**Comment by bensu** [comment] 2015-10-17 09:31
No, that is standard Karma behavior. According to [this](http://stackoverflow.com/questions/16344361/view-karma-test-output-in-a-browser) you can click the "DEBUG" button to open a tab that shows you the console's output. (otherwise you can look at the console directly).

**Closed by bensu** 2015-10-17 09:31 UTC
Labels: bug
